const employeeData = [
    {
      id: 1,
      name: "Đặng Mạnh Hùng",
      company: "Thăng Long",
      department: "R & D Center",
      time: "8:30",
      device: "Thiết bị 1",
    },
    {
      id: 2,
      name: "Phạm Thị Liên",
      company: "Thăng Long",
      department: "TTCN mới",
      time: "8:36",
      device: "Thiết bị 2",
    },
    {
      id: 3,
      name: "Nguyễn Thị Nhung",
      company: "Thăng Long",
      department: "Hành chính nhân sự",
      time: "8:39",
      device: "Thiết bị 1",
    },
    {
      id: 4,
      name: "Trần Thị Quỳnh Anh",
      company: "Thăng Long",
      department: "Quản lý dự án",
      time: "8:40",
      device: "Thiết bị 1",
    },
    {
      id: 5,
      name: "Đỗ Ngọc Hoàng",
      company: "Thăng Long",
      department: "TTCN mới",
      time: "9:30",
      device: "Thiết bị 1",
    },
    {
      id: 6,
      name: "Lê Thị Thùy Linh",
      company: "Thăng Long",
      department: "Pháp chế đấu thầu",
      time: "9:36",
      device: "Thiết bị 1",
    },
    {
      id: 7,
      name: "Bùi Nguyễn Hải Anh",
      company: "Thăng Long",
      department: "TTCN mới",
      time: "9:45",
      device: "Thiết bị 1",
    },
    {
      id: 8,
      name: "Phạm Văn Minh",
      company: "Thăng Long",
      department: "TTCN mới",
      time: "9:50",
      device: "Thiết bị 1",
    },
    {
      id: 9,
      name: "Nguyễn Thị Liêm",
      company: "Thăng Long",
      department: "TTCN mới",
      time: "9:55",
      device: "Thiết bị 1",
    },
    {
      id: 10,
      name: "Nguyễn Hữu Hoàn",
      company: "Thăng Long",
      department: "TTCN mới",
      time: "10:30",
      device: "Thiết bị 1",
    },
    {
        id: 11,
        name: "Nguyễn Thế Anh",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "80:30",
        device: "Thiết bị 1",
      },
      {
        id: 12,
        name: "Vương Công Minh",
        company: "Thăng Long",
        department: "R & D Center",
        time: "18:15",
        device: "Thiết bị 1",
      },
      {
        id: 13,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 14,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 15,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 16,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 17,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 18,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 19,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 20,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 21,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 22,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 23,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 24,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 25,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 26,
        name: "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 27,
        name: "Nguyễn Hữu Hoàn",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "10:30",
        device: "Thiết bị 1",
      },
  ];
  
  export default employeeData;
  