import avatar from "../../assets/istockphoto-1337144146-612x612.jpg"

const employeeData = [
    {
      id: 1,
      avatar : avatar,
      name:  "Đặng Mạnh Hùng",
      company: "Thăng Long",
      department: "R & D Center",
      time: "8:30",
      device: "Thiết bị 1",
    },
    {
      id: 2,
      avatar : avatar,
      name:  "Phạm Thị Liên",
      company: "Thăng Long",
      department: "TTCN mới",
      time: "8:36",
      device: "Thiết bị 2",
    },
    {
      id: 3,
      avatar : avatar,
      name:  "Nguyễn Thị Nhung",
      company: "Thăng Long",
      department: "Hành chính nhân sự",
      time: "8:39",
      device: "Thiết bị 1",
    },
    {
      id: 4,
      avatar : avatar,
      name:  "Trần Thị Quỳnh Anh",
      company: "Thăng Long",
      department: "Quản lý dự án",
      time: "8:40",
      device: "Thiết bị 1",
    },
    {
      id: 5,
      avatar : avatar,
      name:  "Đỗ Ngọc Hoàng",
      company: "Thăng Long",
      department: "TTCN mới",
      time: "9:30",
      device: "Thiết bị 1",
    },
    {
      id: 6,
      avatar : avatar,
      name:  "Lê Thị Thùy Linh",
      company: "Thăng Long",
      department: "Pháp chế đấu thầu",
      time: "9:36",
      device: "Thiết bị 1",
    },
    {
      id: 7,
      avatar : avatar,
      name:  "Bùi Nguyễn Hải Anh",
      company: "Thăng Long",
      department: "TTCN mới",
      time: "9:45",
      device: "Thiết bị 1",
    },
    {
      id: 8,
      avatar : avatar,
      name:  "Phạm Văn Minh",
      company: "Thăng Long",
      department: "TTCN mới",
      time: "9:50",
      device: "Thiết bị 1",
    },
    {
      id: 9,
      avatar : avatar,
      name:  "Nguyễn Thị Liêm",
      company: "Thăng Long",
      department: "TTCN mới",
      time: "9:55",
      device: "Thiết bị 1",
    },
    {
      id: 10,
      avatar : avatar,
      name:  "Nguyễn Hữu Hoàn",
      company: "Thăng Long",
      department: "TTCN mới",
      time: "10:30",
      device: "Thiết bị 1",
    },
    {
        id: 11,
        avatar : avatar,
        name:  "Nguyễn Thế Anh",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "80:30",
        device: "Thiết bị 1",
      },
      {
        id: 12,
        avatar : avatar,
        name:  "Vương Công Minh",
        company: "Thăng Long",
        department: "R & D Center",
        time: "18:15",
        device: "Thiết bị 1",
      },
      {
        id: 13,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 14,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 15,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 16,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 17,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 18,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 19,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 20,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 21,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 22,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 23,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 24,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 25,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 26,
        avatar : avatar,
        name:  "Nguyễn Thị Liêm",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "9:55",
        device: "Thiết bị 1",
      },
      {
        id: 27,
        avatar : avatar,
        name:  "Nguyễn Hữu Hoàn",
        company: "Thăng Long",
        department: "TTCN mới",
        time: "10:30",
        device: "Thiết bị 1",
      },
  ];
  
  export default employeeData;
  